AWSTemplateFormatVersion: "2010-09-09"
Description: "DIO – Template mínimo: S3 (trigger) + Lambda + IAM. Sem ciclos de dependência."

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: { Service: lambda.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  ProcessFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.11
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 128
      Code:
        ZipFile: |
          import json
          def handler(event, context):
              print("Evento S3 recebido:", json.dumps(event))
              return {"status": "ok"}

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ProcessFunction
      Principal: s3.amazonaws.com

  InputBucket:
    Type: AWS::S3::Bucket
    DependsOn: LambdaInvokePermission # garante a permissão antes de criar a notificação
    Properties:
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt ProcessFunction.Arn

Outputs:
  BucketName:
    Value: !Ref InputBucket
    Description: "Bucket para fazer upload e acionar a Lambda"
  LambdaName:
    Value: !Ref ProcessFunction
    Description: "Função Lambda acionada pelo S3"
  NextStepCLI:
    Value: !Sub "aws s3 cp arquivo.txt s3://${InputBucket}/"
    Description: "Comando para testar o trigger via CLI"
